export function generateFingerprint(
  host: string,
  uri: string,
): Record<string, string[]> {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  const lastModified = `${pad(now.getMonth() + 1)}/${pad(now.getDate())}/${now.getFullYear()} ${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;

  // Using an array of entries to preserve insertion order
  const entries: [string, string[]][] = [
    [
      '0',
      [
        'length',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenX',
        'screenY',
        'screenLeft',
        'screenTop',
        'TEMPORARY',
        'n.maxTouchPoints',
      ],
    ],
    [
      '1',
      [
        'devicePixelRatio',
        'PERSISTENT',
        'd.childElementCount',
        'd.ELEMENT_NODE',
        'd.DOCUMENT_POSITION_DISCONNECTED',
      ],
    ],
    ['2', ['d.ATTRIBUTE_NODE', 'd.DOCUMENT_POSITION_PRECEDING']],
    ['3', ['d.TEXT_NODE']],
    ['4', ['d.CDATA_SECTION_NODE', 'd.DOCUMENT_POSITION_FOLLOWING']],
    ['5', ['d.ENTITY_REFERENCE_NODE']],
    ['6', ['d.ENTITY_NODE']],
    ['7', ['d.PROCESSING_INSTRUCTION_NODE']],
    [
      '8',
      ['n.deviceMemory', 'd.COMMENT_NODE', 'd.DOCUMENT_POSITION_CONTAINS'],
    ],
    ['9', ['d.nodeType', 'd.DOCUMENT_NODE']],
    ['10', ['d.DOCUMENT_TYPE_NODE']],
    ['11', ['d.DOCUMENT_FRAGMENT_NODE']],
    ['12', ['d.NOTATION_NODE']],
    [
      '16',
      ['n.hardwareConcurrency', 'd.DOCUMENT_POSITION_CONTAINED_BY'],
    ],
    ['32', ['d.DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC']],
    ['1392', ['outerHeight']],
    ['2560', ['outerWidth']],
    [
      'o',
      [
        'window',
        'self',
        'document',
        'location',
        'customElements',
        'history',
        'navigation',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'frames',
        'top',
        'parent',
        'frameElement',
        'navigator',
        'external',
        'screen',
        'visualViewport',
        'clientInformation',
        'styleMedia',
        'crypto',
        'scheduler',
        'performance',
        'trustedTypes',
        'indexedDB',
        'localStorage',
        'sessionStorage',
        'chrome',
        'cookieStore',
        'caches',
        'documentPictureInPicture',
        'sharedStorage',
        'viewport',
        'launchQueue',
        'speechSynthesis',
        'globalThis',
        'JSON',
        'Math',
        'Intl',
        'Atomics',
        'Reflect',
        'console',
        'CSS',
        'WebAssembly',
        'GPUBufferUsage',
        'GPUColorWrite',
        'GPUMapMode',
        'GPUShaderStage',
        'GPUTextureUsage',
        'n.scheduling',
        'n.userActivation',
        'n.geolocation',
        'n.plugins',
        'n.mimeTypes',
        'n.webkitTemporaryStorage',
        'n.webkitPersistentStorage',
        'n.connection',
        'n.windowControlsOverlay',
        'n.protectedAudience',
        'n.bluetooth',
        'n.clipboard',
        'n.credentials',
        'n.keyboard',
        'n.managed',
        'n.mediaDevices',
        'n.storage',
        'n.serviceWorker',
        'n.virtualKeyboard',
        'n.wakeLock',
        'n.userAgentData',
        'n.locks',
        'n.login',
        'n.ink',
        'n.mediaCapabilities',
        'n.devicePosture',
        'n.hid',
        'n.mediaSession',
        'n.permissions',
        'n.presentation',
        'n.serial',
        'n.gpu',
        'n.usb',
        'n.xr',
        'n.storageBuckets',
        'd.location',
        'd.implementation',
        'd.documentElement',
        'd.body',
        'd.head',
        'd.images',
        'd.embeds',
        'd.plugins',
        'd.links',
        'd.forms',
        'd.scripts',
        'd.defaultView',
        'd.anchors',
        'd.applets',
        'd.scrollingElement',
        'd.featurePolicy',
        'd.timeline',
        'd.children',
        'd.firstElementChild',
        'd.lastElementChild',
        'd.activeElement',
        'd.styleSheets',
        'd.fonts',
        'd.fragmentDirective',
        'd.childNodes',
        'd.firstChild',
        'd.lastChild',
      ],
    ],
    [
      'F',
      [
        'closed',
        'crossOriginIsolated',
        'credentialless',
        'n.webdriver',
        'n.deprecatedRunAdAuctionEnforcesKAnonymity',
        'd.xmlStandalone',
        'd.hidden',
        'd.wasDiscarded',
        'd.prerendering',
        'd.webkitHidden',
        'd.fullscreen',
        'd.webkitIsFullScreen',
      ],
    ],
    [
      'x',
      [
        'opener',
        'onsearch',
        'onappinstalled',
        'onbeforeinstallprompt',
        'onbeforexrselect',
        'onabort',
        'onbeforeinput',
        'onbeforematch',
        'onbeforetoggle',
        'onblur',
        'oncancel',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncommand',
        'oncontentvisibilityautostatechange',
        'oncontextlost',
        'oncontextmenu',
        'oncontextrestored',
        'oncuechange',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onerror',
        'onfocus',
        'onformdata',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onmousewheel',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onscrollend',
        'onsecuritypolicyviolation',
        'onseeked',
        'onseeking',
        'onselect',
        'onslotchange',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'ontoggle',
        'onvolumechange',
        'onwaiting',
        'fence',
        'n.doNotTrack',
        'd.doctype',
        'd.xmlEncoding',
        'd.xmlVersion',
        'd.currentScript',
        'd.onreadystatechange',
        'd.all',
      ],
    ],
    [`https://${host}`, ['origin']],
    ['u', ['event', 'undefined']],
    [
      'T',
      [
        'isSecureContext',
        'originAgentCluster',
        'offscreenBuffering',
        'n.pdfViewerEnabled',
        'n.cookieEnabled',
        'n.onLine',
        'd.fullscreenEnabled',
        'd.webkitFullscreenEnabled',
        'd.pictureInPictureEnabled',
        'd.isConnected',
      ],
    ],
    [
      'N',
      [
        'alert',
        'atob',
        'blur',
        'btoa',
        'cancelAnimationFrame',
        'cancelIdleCallback',
        'captureEvents',
        'clearInterval',
        'clearTimeout',
        'close',
        'confirm',
        'createImageBitmap',
        'fetch',
        'find',
        'focus',
        'getComputedStyle',
        'getSelection',
        'matchMedia',
        'moveBy',
        'moveTo',
        'open',
        'postMessage',
        'print',
        'prompt',
        'queueMicrotask',
        'releaseEvents',
        'reportError',
        'requestAnimationFrame',
        'requestIdleCallback',
        'resizeBy',
        'resizeTo',
        'scroll',
        'scrollBy',
        'scrollTo',
        'setInterval',
        'setTimeout',
        'stop',
        'structuredClone',
        'addEventListener',
        'dispatchEvent',
        'removeEventListener',
        'Object',
        'Function',
        'Number',
        'parseFloat',
        'parseInt',
        'Boolean',
        'String',
        'Symbol',
        'Date',
        'Promise',
        'RegExp',
        'Error',
        'AggregateError',
        'EvalError',
        'RangeError',
        'ReferenceError',
        'SyntaxError',
        'TypeError',
        'URIError',
        'ArrayBuffer',
        'Uint8Array',
        'Int8Array',
        'Uint16Array',
        'Int16Array',
        'Uint32Array',
        'Int32Array',
        'BigUint64Array',
        'BigInt64Array',
        'Uint8ClampedArray',
        'Float32Array',
        'Float64Array',
        'DataView',
        'Map',
        'BigInt',
        'Set',
        'WeakMap',
        'WeakSet',
        'Proxy',
        'WeakRef',
        'decodeURI',
        'decodeURIComponent',
        'encodeURI',
        'encodeURIComponent',
        'escape',
        'unescape',
        'eval',
        'isFinite',
        'isNaN',
        'XMLHttpRequest',
        'Request',
        'Response',
        'Headers',
        'URL',
        'URLSearchParams',
        'Blob',
        'File',
        'FileReader',
        'FormData',
        'WebSocket',
        'Worker',
        'Event',
        'CustomEvent',
        'EventTarget',
        'Node',
        'Element',
        'Document',
        'HTMLElement',
        'HTMLDivElement',
        'HTMLSpanElement',
        'HTMLInputElement',
        'd.getElementById',
        'd.getElementsByClassName',
        'd.getElementsByTagName',
        'd.querySelector',
        'd.querySelectorAll',
        'd.createElement',
        'd.createTextNode',
        'd.createDocumentFragment',
        'd.appendChild',
        'd.removeChild',
        'd.insertBefore',
        'd.addEventListener',
        'd.removeEventListener',
        'd.dispatchEvent',
      ],
    ],
    ['E', ['Array']],
    ['Infinity', ['Infinity']],
    ['NaN', ['NaN']],
    ['Google Inc.', ['n.vendor']],
    ['Mozilla', ['n.appCodeName']],
    ['Netscape', ['n.appName']],
    [
      '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
      ['n.appVersion'],
    ],
    ['Win32', ['n.platform']],
    ['Gecko', ['n.product']],
    [
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
      ['n.userAgent'],
    ],
    ['en-US', ['n.language']],
    ['en-US,en', ['n.languages']],
    ['about:blank', ['d.URL', 'd.documentURI']],
    ['BackCompat', ['d.compatMode']],
    ['UTF-8', ['d.characterSet', 'd.charset', 'd.inputEncoding']],
    ['text/html', ['d.contentType']],
    [host, ['d.domain']],
    [uri, ['d.referrer', 'd.baseURI']],
    ['s', ['d.cookie']],
    [lastModified, ['d.lastModified']],
    ['complete', ['d.readyState']],
    ['off', ['d.designMode']],
    ['visible', ['d.visibilityState', 'd.webkitVisibilityState']],
    ['', ['d.adoptedStyleSheets']],
    ['#document', ['d.nodeName']],
  ];

  const result: Record<string, string[]> = {};
  for (const [key, value] of entries) {
    result[key] = value;
  }
  return result;
}
