/* eslint-disable @typescript-eslint/naming-convention */
/**
 * @group Constants
 * @groupDescription Amaris Chemical Solutions product categories.
 * @source
 */

export enum ProductCategory {
  ACCELERATORS_RETARDERS = 7330,
  /** Acidulants are food-grade acids used to enhance flavor, regulate pH, and act as preservatives in food and beverage products. Common types include citric acid (from citrus), malic acid (found in apples), tartaric acid (from grapes), and phosphoric acid (used in sodas). These additives provide a tangy or sour taste in candies, soft drinks, jams, and dairy products while also inhibiting microbial growth to extend shelf life. Natural acidulants, like those derived from fruits, align with clean-label trends, while synthetic variants ensure cost-effective production. As versatile and essential ingredients, acidulants help achieve the desired taste, safety, and stability in a wide range of culinary and industrial applications. */
  ACIDULANTS = 144,
  ACTIVE_INGREDIENT = 1500,
  ACTIVE_PHARMACEUTICAL_INGREDIENTS_APIS = 134,
  ADDITIVES = 199,
  ADHESION_PROMOTERS = 225,
  /** Admixtures are specialized chemical additives used in concrete and mortar to enhance performance, workability, and durability. Admixtures enable precise control over concrete behavior, allowing for low-water mixes, faster construction, or extended workability in challenging conditions. They also support sustainable practices by reducing cement content and improving longevity. From high-strength structures to decorative finishes, admixtures provide tailored solutions for modern construction needs while meeting quality and efficiency demands. */
  ADMIXTURES = 166,
  /** Agricultural chemicals are substances used to enhance crop production and protect plants from pests, diseases, and weeds. They include pesticides (insecticides, herbicides, fungicides), fertilizers (NPK, micronutrients), and soil conditioners. These chemicals boost yields, improve soil fertility, and ensure food security, but require careful management to minimize environmental and health risks. */
  AGRICULTURAL_CHEMICALS = 126,
  /** Analytical Reagents are high-purity chemicals used in laboratories for qualitative and quantitative analysis. They help in detecting, measuring, or identifying substances through various chemical reactions. These reagents must meet strict quality standards to ensure accuracy and reliability in tests, such as titration, spectroscopy, and chromatography. */
  ANALYTICAL_REAGENTS_LABORATORY_CHEMICALS = 2069,
  /** Animal Feed Additives are substances added to livestock and poultry feed to enhance nutrition, improve growth, and maintain animal health. These additives include vitamins, minerals, amino acids, probiotics, enzymes, and antibiotics. They help optimize digestion, boost immunity, and increase feed efficiency, leading to better meat, milk, and egg production. Some additives, like prebiotics and phytogenics, promote gut health naturally, while others, such as antioxidants, preserve feed quality. */
  ANIMAL_FEED_ADDITIVES = 131,
  /** anti corrosion agents are chemicals used to protect metal surfaces from corrosion, oxidation, and rust. They form a protective layer on the surface, preventing the metal from reacting with the environment. Common types include zinc, nickel, chromium, and copper. They are used in a variety of applications, including automotive parts, construction materials, and industrial equipment. */
  ANTI_CORROSION_AGENTS = 201,
  /** Anti-corrosion coatings are protective layers applied to metal surfaces to prevent rust and degradation caused by moisture, chemicals, or environmental exposure. These coatings—including epoxy, zinc-rich primers, and polyurethane—create a durable barrier that extends the lifespan of structures like bridges, pipelines, and industrial equipment. Advanced options feature self-healing properties or nanotechnology for enhanced performance. Ideal for harsh environments, they reduce maintenance costs while ensuring long-term structural integrity. */
  ANTI_CORROSION_COATINGS = 171,
  ANTIBIOTICS = 137,
  /** Antifoaming agents are specialty chemicals used to control or eliminate unwanted foam in water treatment and industrial processes. They work by breaking down surface tension or destabilizing foam bubbles, preventing overflow, inefficiencies, and operational disruptions. Common types include silicone-based, oil-based, and water-soluble polyglycol compounds. These agents are widely applied in wastewater treatment, fermentation, cooling systems, and chemical processing to maintain smooth operations, improve product quality, and reduce downtime */
  ANTIFOAMING_AGENTS = 91,
  /** Antioxidants are compounds that prevent or slow down oxidation, a chemical reaction that can damage food and beverages by causing rancidity, color changes, and nutrient loss. They help extend shelf life and maintain quality.Below are the two types of antioxidants Natural Antioxidants – Found in vitamins (C, E), polyphenols (in fruits, tea), and carotenoids (in carrots, tomatoes). Synthetic Antioxidants – Such as BHA (butylated hydroxyanisole), BHT (butylated hydroxytoluene), and TBHQ, commonly used in processed foods. */
  ANTIOXIDANTS = 147,
  /** Antioxidants in cosmetics are powerful ingredients that protect the skin from damage caused by free radicals—unstable molecules generated by UV exposure, pollution, and stress. Common antioxidants like vitamin C, vitamin E, green tea extract, and niacinamide neutralize these harmful molecules, preventing premature aging, inflammation, and collagen breakdown. They also brighten skin, even tone, and enhance the effectiveness of sunscreens. Found in serums, moisturizers, and sun care products, antioxidants are a key part of modern skincare for maintaining healthy, youthful skin. */
  ANTIOXIDANTSCOSMETIC = 119,
  ANTISEPTICS_AND_DISINFECTANTS = 138,
  APPLICATION_SPECIFIC_COATINGS = 204,
  AUTOMOTIVE_CHEMICALS = 187,
  /** Baking ingredients are essential components used to create a variety of baked goods, each contributing to texture, flavor, and structure. Key ingredients include flour, which provides structure through gluten formation; sugar, for sweetness and browning; fats, for tenderness and moisture; and leavening agents(such as baking powder, baking soda, or yeast), which help doughs and batters rise.Additional ingredients like salt (for flavor balance), vanilla extract (for aroma), and chocolate or fruits (for added taste and texture) enhance the final product.· */
  BAKING_INGREDIENTS = 210,
  BINDERS_RESINS = 196,
  /** Bio-based Solvents are eco-friendly alternatives to traditional petroleum-derived solvents, made from renewable sources like plants, vegetables, and agricultural waste. These sustainable solvents—such as ethanol from sugarcane, limonene from citrus peels, and lactic acid from corn—offer excellent performance in paints, coatings, adhesives, and cleaning products while significantly reducing VOC emissions and environmental toxicity. As industries shift toward greener chemistry, bio-based solvents provide a biodegradable, low-carbon solution without compromising efficiency. Their use supports circular economies, regulatory compliance, and safer workplaces, making them a smart choice for environmentally conscious businesses and consumers. */
  BIO_BASED_SOLVENTS = 191,
  /** Biochemical Reagents are specialized chemicals used to study biological processes, analyze biomolecules, and perform experiments in molecular biology, biochemistry, and biotechnology. These high-purity reagents are designed to interact with biological systems, enabling research, diagnostics, and drug development. */
  BIOCHEMICAL_REAGENTS = 2075,
  /** Bleaching agents are chemical compounds used to whiten, brighten, or remove stains from materials like fabrics, paper, hair, and even food (e.g., flour). They work by breaking down color-causing molecules through oxidation or reduction. Common types include chlorine-based bleach (strong disinfectants), oxygen-based alternatives (gentler on fabrics), and food-grade agents like benzoyl peroxide (used in flour treatment). */
  BLEACHING_AGENTS_CLEANING_AND_DETERGENT_CHEMICALS = 175,
  /** Builders are water-softening chemicals added to detergents and cleaning products to enhance their effectiveness. They work by neutralizing mineral ions (like calcium and magnesium) in hard water that interfere with cleaning. Common builders include phosphates , zeolites, sodium carbonate (washing soda), and citrates. By preventing soap scum and improving surfactant performance, builders help detergents remove stains more efficiently while reducing residue on fabrics and surfaces.Builders play a crucial but often overlooked role in laundry detergents, dishwashing products, and industrial cleaners. */
  BUILDERS = 174,
  CATALYSTS_SPECIALTY_AND_FINE_CHEMICALS = 181,
  /** Chelating agents are water treatment chemicals that bind and neutralize metal ions (like calcium, magnesium, iron, and heavy metals) to prevent scaling, corrosion, and oxidation. By forming stable, water-soluble complexes, they improve water quality and protect industrial equipment. Common chelants include EDTA (ethylenediaminetetraacetic acid), citric acid, and phosphonates, used in boiler systems, cooling towers, and wastewater treatment. They enhance the efficiency of other treatment chemicals while reducing harmful deposits and metal-induced damage in pipelines and machinery. */
  CHELATING_AGENTS = 92,
  /** Chromatography chemicals are high-purity solvents, buffers, and reagents used to separate, identify, and analyze mixtures in various chromatographic techniques such as HPLC, GC, TLC, and column chromatography. These chemicals ensure optimal resolution, peak shape, and reproducibility in analytical and preparative separations */
  CHROMATOGRAPHY_CHEMICALS = 2071,
  /** Cleaning and detergent chemicals are specially formulated substances designed to remove dirt, stains, germs, and odors from surfaces, fabrics, and utensils. They include surfactants (which break down grease and grime), alkalis (like sodium hydroxide for tough stains), acids (such as citric acid for limescale removal), disinfectants (e.g., bleach or hydrogen peroxide), and enzymes (to break down protein or starch-based stains). Proper use ensures effective sanitation while minimizing skin irritation or chemical residues. Industrial and household cleaners vary in strength, with regulations ensuring safety in food-contact and residential spaces. */
  CLEANING_AND_DETERGENT_CHEMICALS = 172,
  /** Coagulants and flocculants are essential water treatment chemicals that remove suspended particles and clarify water. Coagulants (like alum or ferric chloride) neutralize particle charges, causing small clumps to form, while flocculants (such as polyacrylamide) bind these clumps into larger, settleable flocs. This process is widely used in drinking water treatment, wastewater plants, and industrial systems to improve filtration and reduce turbidity. Their efficient use ensures cleaner, safer water by effectively removing contaminants. */
  COAGULANTS_AND_FLOCCULANTS = 86,
  /** Colorants (pigments and dyes) are chemicals used to add color to plastics, textiles, and coatings. Pigments, like titanium dioxide, are insoluble and provide opaque, UV-resistant colors, while dyes, such as azo compounds, dissolve for vibrant, transparent hues. They enhance both aesthetics and functionality (e.g., color-coding wires) while evolving toward safer, eco-friendly formulas. */
  COLORANTS_PIGMENTS_DYES = 109,
  /** Colorants are additives used to enhance or restore the visual appeal of food and beverages. They can be either natural (derived from plants, minerals, or animals) or synthetic (artificially produced). Common natural colorants include turmeric (yellow), beetroot extract (red), and chlorophyll (green), while synthetic ones include Allura Red (E129) and Tartrazine (E102). Colorants play a key role in consumer perception, influencing taste expectations and product attractiveness. However, some synthetic dyes have been linked to allergies and hyperactivity, leading to a growing demand for natural alternatives. */
  COLORANTSFOOD = 148,
  /** Concrete Repair Chemicals are specialized materials used to restore damaged or deteriorating concrete structures, ensuring structural integrity and longevity. These solutions include epoxy injections for crack filling, polymer-modified mortars for spall repairs, and corrosion inhibitors to protect reinforcement bars. They provide high adhesion, durability, and resistance to environmental stress, making them ideal for bridges, parking structures, and industrial floors. Whether for minor cracks or major structural rehabilitation, these chemicals offer cost-effective solutions to extend the service life of concrete assets. */
  CONCRETE_REPAIR_CHEMICALS = 170,
  /** Construction Chemicals are specialized compounds used to enhance the performance, durability, and efficiency of building materials and structures. These additives play a critical role in modern construction by improving the properties of concrete, mortar, adhesives, and coatings. Key types include concrete admixtures (water reducers, accelerators, retarders), waterproofing agents, repair mortars, protective coatings, and sealants. They help achieve faster curing times, increased strength, crack resistance, weatherproofing, and corrosion protection. From high-rise buildings to infrastructure projects, construction chemicals ensure longevity, safety, and cost-effectiveness while meeting stringent quality standards. */
  CONSTRUCTION_CHEMICALS = 165,
  /** Corrosion inhibitors are specialized chemicals added to water systems to protect metal surfaces from degradation caused by oxidation, acidity, or scaling. They form a protective film on pipes, boilers, and cooling systems, preventing rust and prolonging equipment life. */
  CORROSION_INHIBITORS = 89,
  /** Cosmetic and personal care chemicals are ingredients used in products like skincare, haircare, makeup, and hygiene items to enhance appearance, cleanse, or protect the body. These include emulsifiers, preservatives, fragrances, surfactants, and active compounds like vitamins or sunscreens. While many are safe, some synthetic chemicals (e.g., parabens, sulfates, or phthalates) have raised health and environmental concerns, leading to a growing demand for natural or organic alternatives. Regulations ensure safety, but ingredient transparency remains a key consumer priority. */
  COSMETIC_AND_PERSONAL_CARE_CHEMICALS = 112,
  /** Disinfectants and biocides are chemicals used to kill or control harmful microorganisms like bacteria, viruses, and algae in water treatment. Common disinfectants include chlorine, ozone, and UV light, which destroy pathogens in drinking water and wastewater. Biocides (like bromine, chlorine dioxide, and hydrogen peroxide) are used in industrial systems (cooling towers, pipelines) to prevent microbial growth, biofilm formation, and fouling. These chemicals ensure safe, clean water by eliminating health risks and maintaining system efficiency. */
  DISINFECTANTS_AND_BIOCIDES = 87,
  /** Dough conditioners are food additives used to improve the texture, elasticity, and handling properties of dough in baking. They help strengthen gluten formation, enhance dough stability, and extend shelf life by preventing staling. Widely used in commercial bread production, dough conditioners ensure consistent quality, better volume, and longer freshness in baked goods while reducing processing time. */
  DOUGH_CONDITIONERS = 212,
  DRIERS = 200,
  /** Dust suppressants are chemicals or solutions applied to control airborne dust particles in mining, construction, and industrial sites. They work by binding fine particles together or forming a protective crust on surfaces. Common types include water sprays, hygroscopic salts (like calcium chloride), polymers, and bio-based binders. These agents improve air quality, safety, and regulatory compliance while reducing erosion and equipment wear. */
  DUST_SUPPRESSANTS = 99,
  DYES_AND_PIGMENTS = 159,
  ELECTRONIC_CHEMICALS = 180,
  /** Emollients are moisturizing agents used in cosmetics and personal care products to soften, smooth, and hydrate the skin by forming a protective barrier that prevents moisture loss. Common emollients include natural oils (like jojoba or coconut oil), butters (such as shea or cocoa butter), and synthetic compounds (like silicones or fatty alcohols). They are key ingredients in lotions, creams, lip balms, and conditioners, helping to improve skin texture and relieve dryness. Emollients are especially beneficial for sensitive or eczema-prone skin, providing long-lasting hydration and improving skin elasticity. */
  EMOLLIENTS = 113,
  /** Emulsifiers are food additives that help mix two immiscible liquids, such as oil and water, by reducing surface tension and stabilizing the mixture. Commonly used emulsifiers include lecithin (from soy or eggs), mono- and diglycerides, and polysorbates. */
  EMULSIFIERS = 146,
  /** Environmental and Green Chemicals are sustainable, eco-friendly alternatives designed to minimize pollution, reduce toxicity, and lower carbon footprints. These chemicals are derived from renewable sources, biodegradable materials, or engineered for safer decomposition, making them ideal for industries like agriculture, manufacturing, and cleaning.By replacing traditional hazardous substances, green chemicals support circular economies, energy efficiency, and healthier ecosystems. Businesses and consumers alike benefit from their role in combating climate change and promoting responsible resource use. */
  ENVIRONMENTAL_AND_GREEN_CHEMICALS = 189,
  /** Enzymes are natural protein-based catalysts that accelerate chemical reactions in cleaning, food processing, and industrial applications without being consumed in the process. In detergents and cleaners, they target specific stains: proteases break down protein-based stains (blood, food), amylases tackle carbohydrates (starches), lipases dissolve fats/oils, and cellulases help maintain fabric softness. */
  ENZYMES = 176,
  /** Excipients are the inactive ingredients mixed with an active pharmaceutical ingredient (API) to create a safe, stable, and easily deliverable medication.  */
  EXCIPIENTS = 135,
  /** Explosives and blasting agents are high-energy materials used in mining, construction, and demolition to break rock or structures efficiently. Common types include ANFO (ammonium nitrate/fuel oil), emulsion explosives, and dynamite. They release rapid gas expansion upon detonation, fracturing hard materials with precision. Strict safety protocols are required for storage, handling, and environmental impact mitigation. */
  EXPLOSIVES_AND_BLASTING_AGENTS = 100,
  /** Agricultural fertilizers are natural or synthetic substances added to soil or plants to provide essential nutrients that promote healthy growth and increase crop yields. They primarily supply nitrogen (N), phosphorus (P), and potassium (K), along with secondary nutrients like calcium, magnesium, and sulfur. */
  FERTILIZERS = 127,
  FILLERS_EXTENDERS = 223,
  /** Fillers and reinforcements are additives used to improve the strength, durability, and cost-effectiveness of plastics and composites. Fillers like calcium carbonate or talc reduce material costs while enhancing properties like stiffness, while reinforcements such as glass or carbon fibers significantly boost mechanical strength and heat resistance. These additives enable tailored performance for applications ranging from everyday packaging to high-tech aerospace components. */
  FILLERS_AND_REINFORCEMENTS = 110,
  FINISHING_AGENTS = 162,
  /** Flame retardants are chemicals added to plastics, textiles, and construction materials to slow or prevent fire spread. They work by inhibiting combustion (e.g., releasing flame-smothering gases) or forming protective char layers. Used in electronics, furniture, and wiring, they enhance safety but face scrutiny over toxicity (e.g., PBDEs), driving demand for eco-friendly alternatives like phosphorus-nitrogen systems. */
  FLAME_RETARDANTS = 108,
  /** Flavour enhancers are additives that intensify or improve the taste and aroma of food and beverages without contributing their own distinct flavor. They work by stimulating taste receptors, particularly umami (savory) sensations, making food more palatable. */
  FLAVOR_ENHANCERS = 143,
  /** Flocculants and coagulants are chemicals used to remove suspended particles from water. Coagulants like alum neutralize particle charges, forming small clumps, while flocculants like polyacrylamide bind these clumps into larger, settleable masses for easy removal. They’re vital in water treatment, mining, and industrial processes to clarify water, manage sludge, and treat wastewater efficiently. */
  FLOCCULANTS_AND_COAGULANTS = 97,
  /** Food and Beverage Chemicals are specialized ingredients that enhance safety, quality, texture, flavor, and shelf life in consumable products. These include preservatives (e.g., citric acid, sodium benzoate), emulsifiers (e.g., lecithin), stabilizers (e.g., xanthan gum), and acidity regulators (e.g., phosphates). Natural and synthetic options cater to diverse needs—from dairy and baked goods to beverages and packaged foods—while complying with strict food-grade standards (FDA, EFSA).By ensuring product consistency and safety, these chemicals play a vital role in global food supply chains. */
  FOOD_AND_BEVERAGE_CHEMICALS = 141,
  /** Fragrances are aromatic compounds added to cleaning products, personal care items, and household goods to impart pleasant scents and mask unpleasant odors. They can be derived from natural sources (essential oils like lavender or citrus) or synthetic compounds (engineered for consistency and cost-effectiveness). In detergents, soaps, and air fresheners, fragrances enhance user experience, with popular profiles including floral, fresh, woody, or fruity notes. */
  FRAGRANCES = 178,
  /** Fragrances and essential oils are key aromatic ingredients that enhance the sensory appeal of cosmetics and personal care products. Synthetic fragrances offer consistent, long-lasting scents, while essential oils (like lavender, tea tree, or citrus extracts) provide natural fragrance along with potential therapeutic benefits.Brands are now prioritizing transparent labeling and clean fragrance alternatives to cater to sensitive skin and eco-conscious consumers. */
  FRAGRANCES_AND_ESSENTIAL_OILS = 117,
  /** Frothers are surface-active agents used in mineral flotation to create stable foam, enabling the separation of valuable minerals from ore. They reduce water’s surface tension, allowing air bubbles to selectively carry hydrophobic particles to the surface while hydrophilic waste sinks. Critical for efficiency in mining, they require precise dosing to balance foam stability and mineral recovery. */
  FROTHERS = 95,
  /** Laboratory glassware and plasticware are essential tools used for measuring, mixing, heating, storing, and analyzing chemicals and biological samples.Glassware is preferred for high-temperature and corrosive chemicals, while plasticware is ideal for biological samples, disposability, and preventing contamination. Both are crucial in chemistry, biology, and medical labs. */
  GENERAL_LAB_GLASSWARE_PLASTICWARE = 5647,
  /** Laboratory heating and cooling equipment are essential for controlling temperature during experiments, reactions, and sample storage. These devices ensure precise thermal conditions for processes like sterilization, incubation, distillation, and preservation.Used in chemistry, biology, pharmaceuticals, and material science for reactions, sample preparation, and storage under controlled thermal conditions. */
  HEATING_COOLING_EQUIPMENT = 5649,
  /** Humectants are hydrating agents used in cosmetics to attract and retain moisture from the environment or deeper skin layers, ensuring long-lasting hydration. Common humectants like hyaluronic acid, glycerin, and propylene glycol work by binding water to the skin’s surface, plumping fine lines and improving elasticity. Ideal for dry or dehydrated skin, they’re found in serums, moisturizers, and masks. */
  HUMECTANTS = 120,
  HYDRAULIC_FRACTURING_FLUIDS = 156,
  INDUSTRIAL_ADDITIVES = 1394,
  /** Inorganic Standards are high-purity chemical compounds containing known concentrations of metals, anions, or other inorganic elements. They are used for calibration, quality control, and validation in analytical techniques like ICP-MS, AAS, and ion chromatography. */
  INORGANIC_AND_ORGANIC_STANDARDS = 2076,
  /** Laboratory furniture and storage solutions are designed to provide a safe, organized, and efficient workspace for scientific research, experiments, and sample handling. These components ensure proper ergonomics, chemical resistance, and contamination control.Essential in chemistry, biology, medical, and industrial labs to maintain safety, efficiency, and organization. */
  LAB_FURNITURE_STORAGE_SOLUTIONS = 5654,
  /** Laboratory safety equipment and protective gear are essential to minimize risks from chemical, biological, thermal, and mechanical hazards. They ensure the well-being of researchers and compliance with safety regulations. */
  LAB_SAFETY_PROTECTIVE_GEAR = 5652,
  /** Laboratory chemicals are high-purity substances used in scientific research, analysis, and industrial applications across various disciplines, including chemistry, biology, pharmaceuticals, and environmental science. These chemicals are classified based on their grade (e.g., analytical grade, reagent grade, USP, HPLC) to ensure accuracy, safety, and reproducibility in experiments. */
  LABORATORY_CHEMICALS = 2068,
  /** Laboratory equipment and apparatus are essential tools used in scientific experiments and research. They include a wide range of instruments designed for measuring, analyzing, mixing, heating, and storing substances. */
  LABORATORY_EQUIPMENT_APPARATUS = 5646,
  /** Laboratory safety chemicals are specialized substances used to prevent accidents, control hazards, and manage emergencies in labs. They help maintain a safe working environment by handling spills, fires, chemical exposures, and waste disposal */
  LABORATORY_SAFETY_CHEMICALS = 2077,
  /** Leaching agents are chemicals used to extract valuable metals (e.g., gold, copper, uranium) from ores by dissolving them into a solution. Common agents include cyanide (for gold/silver), sulfuric acid (for copper), and thiourea (alternative to cyanide). They enable cost-effective metal recovery from low-grade ores but require strict environmental controls to prevent contamination. */
  LEACHING_AGENTS = 98,
  /** Leavening agents are substances used in baking to produce gas, which creates bubbles and causes dough or batter to rise, resulting in light, airy textures.Each type works differently: baking soda requires an acidic ingredient (like buttermilk), while double-acting baking powder reacts both when mixed and heated. Yeast provides a slower rise with added flavor complexity. Proper use of leavening agents is crucial for achieving the desired structure in breads, cakes, cookies, and pastries, with factors like timing, temperature, and ingredient ratios playing key roles in success. */
  LEAVENING_AGENTS = 211,
  LUBRICANTS = 182,
  /** Measuring and analytical instruments are essential laboratory tools used to quantify, analyze, and characterize samples with precision. These devices ensure accurate data collection for research, quality control, and diagnostic purposes.Widely used in chemistry, biology, pharmaceuticals, environmental science, and clinical diagnostics for research, testing, and quality assurance */
  MEASURING_ANALYTICAL_INSTRUMENTS = 5648,
  /** Microbiology and cell culture reagents are specialized chemicals and biological substances used to grow, maintain, and analyze microorganisms (bacteria, fungi, viruses) and eukaryotic cells in controlled laboratory conditions. These reagents ensure optimal growth conditions, sterility, and experimental accuracy in research, diagnostics, and biopharmaceutical production */
  MICROBIOLOGY_AND_CELL_CULTURE_REAGENTS = 2073,
  /** Microscopy and imaging systems are advanced laboratory instruments used to visualize, analyze, and document samples at microscopic and nanoscopic scales. These systems enable researchers to study cellular structures, material properties, and dynamic processes with high precision.Essential in biology, medicine, material science, nanotechnology, and forensics for research, diagnostics, and quality control. */
  MICROSCOPY_IMAGING_SYSTEMS = 5651,
  /** Mining chemicals are specialized substances used to extract, process, and refine minerals from ores. They include flotation reagents (collectors, frothers) to separate valuable minerals, leaching agents (cyanide, sulfuric acid) to dissolve metals, and solvent extractants for purification. These chemicals improve efficiency and recovery rates but require strict handling to minimize environmental impact. */
  MINING_CHEMICALS = 94,
  /** Mixing and separation devices are essential laboratory tools used to combine substances uniformly or isolate specific components from mixtures. These instruments are crucial for sample preparation, chemical reactions, and purification processes.Widely used in biochemistry, pharmaceuticals, environmental testing, and food science for processes like cell lysis, solvent extraction, and particle analysis. */
  MIXING_SEPARATION_DEVICES = 5650,
  /** Molecular biology reagents are essential chemicals, enzymes, and kits used to isolate, manipulate, analyze, and amplify DNA, RNA, and proteins in genetic research, diagnostics, and biotechnology applications. These high-purity reagents enable precise and reproducible experiments in genomics, PCR, cloning, sequencing, and gene editing. */
  MOLECULAR_BIOLOGY_REAGENTS = 2074,
  /** Monomers are small, reactive molecules that serve as the fundamental building blocks for polymers and plastics. Through polymerization processes (like addition or condensation), they chemically bond together to form long chains or networks, creating materials with diverse properties. Their structure and functionality determine the strength, flexibility, and application of the final plastic product—ranging from packaging to medical devices. */
  MONOMERS = 104,
  /** Nutraceutical ingredients in food and beverage chemicals refer to bioactive compounds derived from natural sources that provide health benefits beyond basic nutrition. These ingredients, such as vitamins, minerals, antioxidants, probiotics, omega-3 fatty acids, and plant extracts, are incorporated into functional foods and beverages to promote wellness, prevent diseases, and enhance overall health. They bridge the gap between food and pharmaceuticals, offering therapeutic effects while being consumed as part of a regular diet. Examples include fortified drinks, protein-enriched snacks, and antioxidant-rich superfoods. The demand for nutraceutical ingredients is growing due to increasing consumer awareness of health and wellness. */
  NUTRACEUTICAL_INGREDIENTS_FOOD = 150,
  NUTRACEUTICAL_INGREDIENTS_PHARMACEUTICAL = 140,
  /** Nutrient supplements in food and beverage chemicals are added to enhance nutritional value, fortify products with essential vitamins and minerals, or replace nutrients lost during processing. Common supplements include vitamins (A, D, B-complex, C), minerals (calcium, iron, zinc), amino acids, omega-3 fatty acids, and fiber. These additives help address dietary deficiencies, improve health benefits, and cater to functional food trends. They must comply with safety regulations (e.g., FDA, EFSA) to ensure proper dosage and bioavailability without compromising taste or shelf life. Examples include fortified cereals, vitamin-enriched drinks, and protein-fortified snacks. */
  NUTRIENT_SUPPLEMENTS = 149,
  OIL_AND_GAS_CHEMICALS = 151,
  CHEMICALS = 20,
  /** Oxidizing agents like chlorine, ozone, and hydrogen peroxide purify water by breaking down contaminants through chemical oxidation. They kill pathogens, remove metals (iron/manganese), and degrade organic pollutants, ensuring safer drinking water and cleaner wastewater. Fast-acting and versatile, they’re essential for disinfection, odor control, and maintaining water quality in treatment plants and industrial systems. */
  OXIDIZING_AGENTS = 93,
  PAINT_COATINGS_CHEMICALS = 195,
  /** Pesticides are chemical or biological substances used to control, repel, or eliminate pests such as insects, weeds, fungi, and rodents that damage crops, spread diseases, or harm the environment. They play a key role in agriculture by protecting yields and ensuring food security. However, excessive or improper use can lead to health risks, environmental pollution, and harm to non-target species. Proper regulation and sustainable alternatives (like integrated pest management) are encouraged to minimize negative effects */
  PESTICIDES_HERBICIDES_INSECTICIDES_FUNGICIDES = 128,
  /** pH adjusters are chemicals used to control the acidity or alkalinity of water in treatment processes. Common acidic adjusters like sulfuric acid and hydrochloric acid lower pH, while alkaline agents such as sodium hydroxide (caustic soda) and lime (calcium hydroxide) raise pH. Maintaining optimal pH (typically 6.5–8.5) ensures effective disinfection, corrosion control, and coagulation in drinking water, wastewater, and industrial systems. Proper pH balance also enhances chemical efficiency and protects infrastructure. */
  PH_ADJUSTERS = 88,
  /** pH modifiers are chemicals used to adjust the acidity or alkalinity of water in industrial, mining, and wastewater treatment processes. Common modifiers include lime (calcium hydroxide) to raise pH, and sulfuric acid or carbon dioxide to lower pH. Proper pH control optimizes chemical reactions, prevents corrosion, and ensures regulatory compliance in effluents. */
  PH_MODIFIERS = 101,
  PHARMACEUTICAL_CHEMICALS = 133,
  PHOTOGRAPHIC_CHEMICALS = 184,
  PIGMENTS = 197,
  /** Plasticizers are additives used to increase the flexibility, durability, and workability of polymers, especially rigid plastics like PVC. By embedding themselves between polymer chains, they reduce intermolecular forces, making the material softer and more pliable. They are widely used in products like cables, flooring, medical tubing, and packaging. */
  PLASTICIZERS = 106,
  PLASTICIZERS_SOFTENERS = 222,
  /** Plastics and polymer manufacturing chemicals are essential compounds used to produce, modify, and enhance synthetic materials. These include monomers (e.g., ethylene, propylene) as building blocks, catalysts to control polymerization, and additives like plasticizers, stabilizers, and flame retardants to improve durability, flexibility, and safety. Processes such as polymerization, polycondensation, and extrusion rely on these chemicals to create a wide range of products—from packaging to automotive parts. */
  PLASTICS_AND_POLYMER_MANUFACTURING_CHEMICALS = 103,
  /** Polymerization initiators are chemicals that kickstart the reaction converting monomers into polymers by generating free radicals, ions, or other active species.These compounds break down under heat, light, or catalysts to form reactive sites, enabling chain growth in plastics like PVC, polystyrene, or acrylics. Their selection impacts polymerization speed, molecular weight, and final polymer properties. */
  POLYMERIZATION_INITIATORS = 105,
  /** Precious metal extraction agents are specialized chemicals designed to selectively dissolve and recover valuable metals like gold, silver, and platinum from ores, electronic waste, or recycled materials. These chemicals enable efficient metal recovery in mining (heap leaching) and e-waste recycling, though strict environmental controls are needed, especially for toxic options like cyanide. Innovations now focus on greener methods, such as bioleaching or halogen-based systems, to reduce ecological impact while maintaining high extraction rates. */
  PRECIOUS_METAL_EXTRACTION_AGENTS = 102,
  /** Preservatives are crucial in cosmetics and personal care products to prevent bacterial, mold, and yeast growth, ensuring product safety and longevity. Common preservatives include parabens, phenoxyethanol, and natural options like potassium sorbate. Brands now emphasize preservative-free or naturally preserved formulas to meet consumer demand for safer, cleaner beauty products. */
  PRESERVATIVES = 115,
  /** Preservatives are chemical substances added to food and beverages to extend shelf life by preventing spoilage caused by microorganisms (bacteria, yeast, mold) and oxidation. They help maintain freshness, flavor, color, and texture while ensuring food safety. */
  PRESERVATIVES_FOOD = 142,
  PYROTECHNIC_CHEMICALS = 188,
  REINFORCING_AGENTS = 221,
  RUBBER_PROCESSING_CHEMICALS = 217,
  /** Scale inhibitors are water treatment chemicals that prevent the formation of hard mineral deposits (like calcium carbonate, sulfate, or silica) in pipes, boilers, and cooling systems. They work by disrupting crystal growth or sequestering scale-forming ions, ensuring efficient heat transfer and uninterrupted water flow. Common types include phosphonates, polyacrylates, and natural polymers. These inhibitors are widely used in industrial processes, desalination plants, and HVAC systems to reduce maintenance, improve energy efficiency, and extend equipment lifespan. */
  SCALE_INHIBITORS_WATER = 90,
  /** Sealants and Adhesives are essential materials used in construction, manufacturing, and DIY projects to bond surfaces or fill gaps. Sealants provide a flexible, waterproof barrier that prevents air, moisture, and dust from penetrating joints, ideal for windows, doors, and bathrooms. Adhesives, on the other hand, create strong, durable bonds between materials like wood, metal, plastic, or ceramics, ensuring structural integrity. Whether for home repairs, automotive work, or industrial use, sealants and adhesives offer reliable solutions for sealing leaks, bonding components, and enhancing durability. */
  SEALANTS_AND_ADHESIVES = 168,
  SOFTENING_AGENTS = 161,
  /** Soil conditioners are materials added to soil to improve its physical properties, such as structure, water retention, aeration, and nutrient availability. They help enhance soil fertility, promote root growth, and support healthy plant development. */
  SOIL_CONDITIONERS = 129,
  /** Solvents (Cleaning) are powerful liquid agents designed to dissolve and remove tough residues like grease, oil, adhesives, and stains. They work by breaking down chemical bonds in dirt, making it easy to wipe or rinse away. Common types include alcohols (e.g., isopropyl alcohol), acetone, and eco-friendly options like citrus-based solvents. Ideal for degreasers, paint thinners, and industrial cleaners, solvents act quickly and evaporate without residue. However, some require careful handling due to flammability or fumes. Modern formulations prioritize low toxicity and biodegradability for safer, sustainable cleaning. */
  SOLVENTS_CLEANING = 177,
  /** Laboratory solvents are high-purity liquids used to dissolve, dilute, extract, or purify substances in chemical, biological, and industrial applications. They play a critical role in experiments, chromatography, synthesis, and sample preparation while ensuring safety and reproducibility. */
  SOLVENTSLAB = 2070,
  SOLVENTSPAINT = 198,
  SOLVENTSPHARMACEUTICAL = 136,
  /** Specialized scientific instruments are advanced, high-precision tools designed for specific research, diagnostic, or industrial applications. These devices enable complex analyses, measurements, and experimental procedures that standard lab equipment cannot perform.Used in pharmaceuticals, nanotechnology, forensics, environmental science, and clinical diagnostics for drug development, material research, and quality control */
  SPECIALIZED_SCIENTIFIC_INSTRUMENTS = 5653,
  SPECIALTY_AND_FINE_CHEMICALS = 179,
  SPECIALTY_COATINGS = 202,
  /** Sealants and Adhesives are essential materials used in construction, manufacturing, and DIY projects to bond surfaces or fill gaps. Sealants provide a flexible, waterproof barrier that prevents air, moisture, and dust from penetrating joints, ideal for windows, doors, and bathrooms. Adhesives, on the other hand, create strong, durable bonds between materials like wood, metal, plastic, or ceramics, ensuring structural integrity. Whether for home repairs, automotive work, or industrial use, sealants and adhesives offer reliable solutions for sealing leaks, bonding components, and enhancing durability. */
  SPECIALTY_COATINGS_ADHESIVES = 1351,
  C2_B7_SPECIALTY_LABORATORY_CHEMICALSSPECIAL_LABORATORY_EQUIPMENT = 7325,
  /** Spectroscopy reagents are high-purity chemicals used to prepare samples, calibrate instruments, and enhance detection in various spectroscopic techniques, including UV-Vis, IR, NMR, atomic absorption (AAS), and mass spectrometry (MS). These reagents ensure accurate, reproducible results by minimizing interference and maintaining optimal analytical conditions. */
  SPECTROSCOPY_REAGENTS = 2072,
  /** Stabilizers (UV, Heat) are additives that protect plastics from sun and heat damage. UV stabilizers (like hindered amines) prevent sunlight-induced fading and cracking, while heat stabilizers (e.g., organotin) maintain integrity during high-temperature processing. Essential for outdoor products (pipes, car parts) and packaging, they extend plastic lifespan under harsh conditions. */
  STABILIZERS_UV_HEAT = 107,
  /** Surfactants (Cleaning) are specialized compounds that form the backbone of most cleaning products, from household detergents to industrial degreasers. These versatile molecules act as nature’s perfect mediators between water and oil – their unique structure features a water-attracting (hydrophilic) head and an oil-attracting (hydrophobic) tail. This dual nature allows surfactants to surround and emulsify grease, dirt, and stains, suspending them in water for easy removal. Whether in your laundry detergent, dish soap, or all-purpose cleaner, surfactants work tirelessly to break down stubborn grime, leaving surfaces clean and residue-free. Their intelligent molecular design makes them indispensable for effective cleaning across countless applications while meeting today’s demands for both performance and environmental responsibility. */
  SURFACTANTSCLEANING = 173,
  /** Surfactants (Surface-Active Agents) are key ingredients in cosmetics and personal care products, primarily used for their cleansing, foaming, and emulsifying properties. They work by reducing surface tension between water and oils, allowing dirt and sebum to be lifted away from skin and hair. */
  SURFACTANTSCOSMETIC = 114,
  SURFACTANTSOIL = 155,
  /** Some, like high-fructose corn syrup (HFCS), are processed from natural sources but linked to health concerns. Sweeteners help reduce sugar intake, manage diabetes, and lower calorie content in products like diet sodas, sugar-free snacks, and baked goods. However, debates exist over their long-term health effects, including metabolic impacts and gut health. */
  SWEETENERS = 145,
  TEXTILE_CHEMICALS = 158,
  /** Thickeners are key ingredients used to modify the viscosity and consistency of cosmetic formulations, creating richer lotions, creamy serums, and stable gels. Common thickeners include natural polymers (like xanthan gum or carrageenan), synthetic agents (such as carbomers), and waxes (like beeswax or cetyl alcohol). They improve product spreadability, stability, and sensory appeal while helping to suspend active ingredients. Modern formulations prioritize skin-friendly thickeners that deliver luxurious textures without compromising performance. */
  THICKENERS = 116,
  TOPICAL_STEROIDS = 1499,
  /** UV filters are essential ingredients in sunscreens and UV-protective cosmetics, designed to shield skin from harmful UVA and UVB rays. They fall into two main categories: chemical filters (like avobenzone or octinoxate), which absorb and neutralize UV radiation, and mineral filters (such as zinc oxide or titanium dioxide), which physically block rays by sitting on the skin’s surface. Choosing the right UV filter ensures both effective sun defense and skin compatibility. */
  UV_FILTERS = 118,
  VULCANIZING_AGENTS = 218,
  /** Wastewater Treatment Chemicals are essential for purifying industrial and municipal water by removing contaminants, pathogens, and pollutants. Advanced solutions like bio-enzymes and eco-friendly oxidants provide sustainable alternatives, reducing sludge formation and chemical residues. By improving water quality for safe discharge or reuse, these treatments protect ecosystems, comply with regulations, and support water conservation. Innovations in green chemistry are making wastewater treatment more efficient, cost-effective, and environmentally responsible. */
  WASTEWATER_TREATMENT_CHEMICALS = 194,
  /** Water Treatment Chemicals are specialized substances used to purify and improve water quality for various applications, including drinking water, industrial processes, wastewater treatment, and cooling systems. These chemicals help remove contaminants, control microbial growth, prevent scaling and corrosion, and adjust pH levels. */
  WATER_TREATMENT_CHEMICALS = 85,
  /** Waterproofing Agents are specialized chemicals or coatings designed to protect surfaces from water damage by creating a moisture-resistant barrier. They are widely used in construction, textiles, and industrial applications to prevent leaks, mold growth, and structural deterioration.These agents can be applied to roofs, foundations, bathrooms, and even fabrics to enhance durability and longevity. Whether for residential, commercial, or infrastructure projects, waterproofing agents provide essential protection against water infiltration, ensuring safety and extending the lifespan of materials. */
  WATERPROOFING_AGENTS = 167,
}
