// AUTO-GENERATED by tools/generate-supplier-constants.js — do not edit by hand.
// Regenerate with: pnpm run generate-supplier-constants

/**
 * The active supplier class names, mirroring the value exports of the
 * `@/suppliers` barrel.
 *
 * This module deliberately imports **nothing**. UI that only needs supplier
 * *names* reads them here instead of calling `SupplierFactory.supplierList()`,
 * which would pull every supplier implementation into the importing entry point's
 * bundle.
 * @category Constants
 * @group Suppliers
 * @source
 */
export const SUPPLIER_CLASS_NAMES = [
  "SupplierAladdinSci",
  "SupplierAlchemieLabs",
  "SupplierAllianceChemical",
  "SupplierAmarisChemicalSolutions",
  "SupplierAmbeed",
  "SupplierAsesChem",
  "SupplierBioFuranChem",
  "SupplierBVV",
  "SupplierCarolina",
  "SupplierCarolinaChemical",
  "SupplierFtfScientific",
  "SupplierGoldAndSilverTesting",
  "SupplierHimedia",
  "SupplierInnovatingScience",
  "SupplierLaballey",
  "SupplierLabChem",
  "SupplierLaboratoriumDiscounter",
  "SupplierLeroChem",
  "SupplierLibertySci",
  "SupplierLiMac",
  "SupplierLoudwolf",
  "SupplierMacklin",
  "SupplierOnyxmet",
  "SupplierS3Chemicals",
  "SupplierSynthetika",
  "SupplierTheLabStockroom",
  "SupplierVWR",
  "SupplierWarchem",
] as const satisfies ReadonlyArray<SupplierClassName>;
