/**
 * Represents a request object with associated hash and file information.
 * This type is used to track and manage requests with their corresponding file data.
 */
export type RequestHashObject = {
  /**
   * The unique hash identifier for the request
   * This is generated by the getRequestHash function which takes some unique identifying
   * attributes of the request (method, path, search params and body) and returns an md5sum
   * of them.
   */
  hash: string;
  /** The file path associated with the request */
  file: string;
  /** The URL object representing the request endpoint */
  url: URL;
};
