import { CACHE } from "@/constants/common";
import { FetchDecoratorResponse } from "@/helpers/fetch";

/**
 * Represents a single node in the doubly-linked list used by {@link HttpLru}.
 * Each node holds a cached HTTP response keyed by its request hash, along with
 * pointers to the previous and next nodes for O(1) reordering.
 *
 * @interface LruNode
 * @source
 */
interface LruNode {
  /** The request hash used as the cache lookup key */
  key: string;
  /** The cached HTTP response data */
  value: FetchDecoratorResponse;
  /** Pointer to the previous (more recently used) node, or `null` if this is the head */
  prev: LruNode | null;
  /** Pointer to the next (less recently used) node, or `null` if this is the tail */
  next: LruNode | null;
}

/** Default maximum number of entries the LRU cache will hold before evicting */
const DEFAULT_CAPACITY = 100;

/**
 * A singleton LRU (Least Recently Used) cache for HTTP responses, backed by
 * `chrome.storage.local` for persistence across browser sessions.
 *
 * The cache uses a doubly-linked list combined with a `Map` for O(1) lookups,
 * insertions, and evictions. When the cache exceeds its configured capacity,
 * the least recently accessed entry is automatically evicted.
 *
 * State is persisted to `chrome.storage.local` on every mutation so that
 * cached responses survive extension restarts and browser closures.
 *
 * @example
 * ```typescript
 * const cache = await HttpLru.getInstance(50);
 * const cached = await cache.getByHash(requestHash);
 * if (!cached) {
 *   const response = await fetchDecorator(url, options);
 *   await cache.putByHash(requestHash, response);
 * }
 * ```
 *
 * @class HttpLru
 * @source
 */
export class HttpLru {
  /** The singleton instance, lazily initialized via {@link HttpLru.getInstance} */
  static #instance: HttpLru | null = null;
  /** Maximum number of entries before the least recently used entry is evicted */
  private capacity: number;
  /** Hash map providing O(1) access to linked-list nodes by request hash */
  private cache: Map<string, LruNode>;
  /** Pointer to the most recently used node (front of the list) */
  private head: LruNode | null;
  /** Pointer to the least recently used node (back of the list) */
  private tail: LruNode | null;

  /**
   * Creates a new HttpLru instance. Private to enforce the singleton pattern —
   * use {@link HttpLru.getInstance} instead.
   *
   * @param capacity - Maximum number of entries to store before evicting (default: {@link DEFAULT_CAPACITY})
   * @source
   */
  private constructor(capacity: number = DEFAULT_CAPACITY) {
    this.capacity = capacity;
    this.cache = new Map();
    this.head = null;
    this.tail = null;
  }

  /**
   * Returns the singleton HttpLru instance, restoring persisted state from
   * `chrome.storage.local` on first access. Subsequent calls return the
   * same in-memory instance without hitting storage.
   *
   * @param capacity - Maximum number of entries (only applied when creating a new instance)
   * @returns The singleton HttpLru instance
   *
   * @example
   * ```typescript
   * const cache = await HttpLru.getInstance();
   * ```
   * @source
   */
  public static async getInstance(capacity: number = DEFAULT_CAPACITY): Promise<HttpLru> {
    if (HttpLru.#instance) {
      return HttpLru.#instance;
    }
    const data = await chrome.storage.local.get([CACHE.HTTP_LRU]);
    if (data[CACHE.HTTP_LRU]) {
      const httplru = new HttpLru(capacity);
      httplru.cache = new Map(Object.entries(data[CACHE.HTTP_LRU].cache));
      httplru.head = data[CACHE.HTTP_LRU].head;
      httplru.tail = data[CACHE.HTTP_LRU].tail;
      HttpLru.#instance = httplru;
      return httplru;
    } else {
      HttpLru.#instance = new HttpLru(capacity);
      return HttpLru.#instance;
    }
  }

  /**
   * Retrieves a cached response by its request hash. This is a convenience
   * wrapper around {@link HttpLru.get} that makes the hash-based lookup
   * intent explicit.
   *
   * @param hash - The request hash generated by {@link generateRequestHash}
   * @returns The cached response, or `null` if no entry exists for the hash
   * @source
   */
  async getByHash(hash: string): Promise<FetchDecoratorResponse | null> {
    return await this.get(hash);
  }

  /**
   * Stores a response in the cache keyed by its request hash. This is a
   * convenience wrapper around {@link HttpLru.put} that makes the hash-based
   * storage intent explicit.
   *
   * @param hash - The request hash generated by {@link generateRequestHash}
   * @param value - The HTTP response to cache
   * @source
   */
  async putByHash(hash: string, value: FetchDecoratorResponse): Promise<void> {
    return await this.put(hash, value);
  }

  /**
   * Retrieves a cached response by key and promotes it to the head of the
   * linked list (marking it as most recently used).
   *
   * @param key - The cache key to look up
   * @returns The cached response if found, or `null` if the key is not in the cache
   * @source
   */
  async get(key: string): Promise<FetchDecoratorResponse | null> {
    if (this.cache.has(key)) {
      const node = this.cache.get(key)!;
      this.moveToHead(node);
      return node.value;
    }
    return null;
  }

  /**
   * Inserts or updates a cached response. If the key already exists, its value
   * is updated and the node is promoted to the head. If the key is new, a new
   * node is created at the head. When the cache exceeds its capacity, the
   * least recently used entry (tail) is evicted.
   *
   * Persists the updated cache state to `chrome.storage.local` after mutation.
   *
   * @param key - The cache key (typically a request hash)
   * @param value - The HTTP response to store
   * @source
   */
  async put(key: string, value: FetchDecoratorResponse): Promise<void> {
    if (this.cache.has(key)) {
      const node = this.cache.get(key)!;
      node.value = value;
      this.moveToHead(node);
    } else {
      const newNode: LruNode = { key, value, prev: null, next: this.head };
      if (this.head) {
        this.head.prev = newNode;
      }
      this.head = newNode;
      if (!this.tail) {
        this.tail = newNode;
      }
      this.cache.set(key, newNode);
      if (this.cache.size > this.capacity) {
        this.cache.delete(this.tail.key);
        this.tail = this.tail.prev;
        if (this.tail) {
          this.tail.next = null;
        } else {
          this.head = null;
        }
      }
    }
    // Save to chrome.storage.local
    await this.saveToStorage();
  }

  /**
   * Detaches a node from its current position in the doubly-linked list and
   * reinserts it at the head, marking it as the most recently used entry.
   * Persists the reordered state to `chrome.storage.local`.
   *
   * @param node - The node to promote to the head of the list
   * @source
   */
  private async moveToHead(node: LruNode): Promise<void> {
    if (node === this.head) {
      return;
    }
    if (node === this.tail) {
      this.tail = node.prev;
    } else if (node.prev) {
      node.prev.next = node.next;
    }
    if (node.next) {
      node.next.prev = node.prev;
    }
    node.prev = null;
    node.next = this.head;
    if (this.head) {
      this.head.prev = node;
    }
    this.head = node;
    // Save to chrome.storage.local after moving node
    await this.saveToStorage();
  }

  /**
   * Serializes the current cache state (map entries, head, and tail pointers)
   * and writes it to `chrome.storage.local` under the `httplru` key.
   * Called internally after every mutation to ensure persistence.
   *
   * @source
   */
  private async saveToStorage(): Promise<void> {
    const cacheData = Object.fromEntries(this.cache);
    await chrome.storage.local.set({
      [CACHE.HTTP_LRU]: {
        cache: cacheData,
        head: this.head,
        tail: this.tail,
      },
    });
  }
}
