name: Update Wiki

on:
  push:
    branches:
      - main # Trigger on pushes to your main branch

jobs:
  update-wiki-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # (Optional) Add steps here to generate your wiki content/filegits in a specific directory

    - name: Push to wiki
      uses: andrew-chen-wang/github-wiki-action@v5
      with:
        token: ${{ secrets.WIKI_ACCESS_TOKEN }}
        path: 'wiki_files'
        commit-message: 'Docs: Auto-sync wiki from repo content'
